DATA_PATH = '../data'
DATA_CACHE_PATH = '../data/cache'
JOBS_PATH = './jobs'
RESULTS_PATH = '../results'
MODEL_CHECKPOINTS_PATH = './models/models_checkpoints'
EMBEDDING_CHECKPOINTS_PATH = './embeddings_checkpoints'